spring.application.name=PaymentService
server.port=9003

# To use multiple instances of the process 9003, 9023, 9033
#server.port=${PORT}

# Eureka Client settings

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.server-url.defaultZone=http://localhost:8761/eureka/